# Notes:
# - The ports are used to define who is the sender and who is the receiver (tests run locally)
# - protocol_type has two options: "simple" and "sender_receiver" (which separates the protocol in two distinct roles)


# Protocol properties. Cannot have both sender and receiver with the same port.
sender=9000
receiver=9001
protocol_type=sender_receiver
use_monitors=true

# fault test properties
fault_min_delay=1000
fault_max_delay=3000
fault_probability=1
fault_test_on=true
fault_conn_fail_min_time=4000
fault_conn_fail_max_time=8000
fault_list=MessageDrop

# Put custom below
ping_timeout=1000