# Notes:
# - The ports are used to define who is the sender and who is the receiver (tests run locally)
# - protocol_type has two options: "simple" and "sender_receiver" (which separates the protocol in two distinct roles)
# - fault_list is a string with fault types: "MessageDrop", "MessageTinker" and "ConnectionDrop" (e.g. fault_list=MessageDrop,ConnectionDrop)


# Protocol properties. Cannot have both sender and receiver with the same port.
sender=9000
receiver=9001
protocol_type=simple
use_monitors=false

# fault test properties
fault_test_on=false
fault_probability=0.5
fault_list=ConnectionDrop,MessageDrop,MessageTinker
fault_start_delay=5000
fault_min_delay=1000
fault_max_delay=4000
fault_conn_fail_min_time=2000
fault_conn_fail_max_time=4000

# Put custom below

# Supports a list of ports (e.g., 9000,9001,9002,etc...)
clients_ports=9000
client_start_delay=7000
client_ops_numb=10000